package com.leo.ssh.domain;
// Generated 2017-4-3 19:26:36 by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Adminroles generated by hbm2java
 */
public class Adminroles implements java.io.Serializable {

	private int rolesid;
	private String rolesname;
	private Set adminses = new HashSet(0);

	public Adminroles() {
	}

	public Adminroles(int rolesid) {
		this.rolesid = rolesid;
	}

	public Adminroles(int rolesid, String rolesname, Set adminses) {
		this.rolesid = rolesid;
		this.rolesname = rolesname;
		this.adminses = adminses;
	}

	public int getRolesid() {
		return this.rolesid;
	}

	public void setRolesid(int rolesid) {
		this.rolesid = rolesid;
	}

	public String getRolesname() {
		return this.rolesname;
	}

	public void setRolesname(String rolesname) {
		this.rolesname = rolesname;
	}

	public Set getAdminses() {
		return this.adminses;
	}

	public void setAdminses(Set adminses) {
		this.adminses = adminses;
	}

}
