package com.leo.ssh.domain;
// Generated 2017-4-3 19:26:36 by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Bigcommodityclass generated by hbm2java
 */
public class Bigcommodityclass implements java.io.Serializable {

	private int bigclassid;
	private String bigclassname;
	private Set commodityclasses = new HashSet(0);

	public Bigcommodityclass() {
	}

	public Bigcommodityclass(int bigclassid, String bigclassname) {
		this.bigclassid = bigclassid;
		this.bigclassname = bigclassname;
	}

	public Bigcommodityclass(int bigclassid, String bigclassname, Set commodityclasses) {
		this.bigclassid = bigclassid;
		this.bigclassname = bigclassname;
		this.commodityclasses = commodityclasses;
	}

	public int getBigclassid() {
		return this.bigclassid;
	}

	public void setBigclassid(int bigclassid) {
		this.bigclassid = bigclassid;
	}

	public String getBigclassname() {
		return this.bigclassname;
	}

	public void setBigclassname(String bigclassname) {
		this.bigclassname = bigclassname;
	}

	public Set getCommodityclasses() {
		return this.commodityclasses;
	}

	public void setCommodityclasses(Set commodityclasses) {
		this.commodityclasses = commodityclasses;
	}

}
