package com.leo.ssh.domain;
// Generated 2017-4-3 19:26:36 by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Commodityclass generated by hbm2java
 */
public class Commodityclass implements java.io.Serializable {

	private Integer commodityClassId;
	private Bigcommodityclass bigcommodityclass;
	private String commodityClassName;
	private Set commodities = new HashSet(0);

	public Commodityclass() {
	}

	public Commodityclass(Bigcommodityclass bigcommodityclass, String commodityClassName) {
		this.bigcommodityclass = bigcommodityclass;
		this.commodityClassName = commodityClassName;
	}

	public Commodityclass(Bigcommodityclass bigcommodityclass, String commodityClassName, Set commodities) {
		this.bigcommodityclass = bigcommodityclass;
		this.commodityClassName = commodityClassName;
		this.commodities = commodities;
	}

	public Integer getCommodityClassId() {
		return this.commodityClassId;
	}

	public void setCommodityClassId(Integer commodityClassId) {
		this.commodityClassId = commodityClassId;
	}

	public Bigcommodityclass getBigcommodityclass() {
		return this.bigcommodityclass;
	}

	public void setBigcommodityclass(Bigcommodityclass bigcommodityclass) {
		this.bigcommodityclass = bigcommodityclass;
	}

	public String getCommodityClassName() {
		return this.commodityClassName;
	}

	public void setCommodityClassName(String commodityClassName) {
		this.commodityClassName = commodityClassName;
	}

	public Set getCommodities() {
		return this.commodities;
	}

	public void setCommodities(Set commodities) {
		this.commodities = commodities;
	}

}
