package com.leo.ssh.domain;
// Generated 2017-2-8 0:23:42 by Hibernate Tools 4.0.1.Final

/**
 * Orderitem generated by hbm2java
 */
public class Orderitem implements java.io.Serializable {

	private Integer orderitemid;
	private Commodity commodity;
	private Order order;
	private Integer quantity;

	public Orderitem() {
	}

	public Orderitem(Commodity commodity, Order order) {
		this.commodity = commodity;
		this.order = order;
	}

	public Orderitem(Commodity commodity, Order order, Integer quantity) {
		this.commodity = commodity;
		this.order = order;
		this.quantity = quantity;
	}

	public Integer getOrderitemid() {
		return this.orderitemid;
	}

	public void setOrderitemid(Integer orderitemid) {
		this.orderitemid = orderitemid;
	}

	public Commodity getCommodity() {
		return this.commodity;
	}

	public void setCommodity(Commodity commodity) {
		this.commodity = commodity;
	}

	public Order getOrder() {
		return this.order;
	}

	public void setOrder(Order order) {
		this.order = order;
	}

	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

}
