package com.leo.ssh.domain;
// Generated 2017-4-3 19:26:36 by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private Integer userid;
	private String useracount;
	private String userpasswork;
	private Boolean userstatus;
	private String username;
	private String userphone;
	private String useraddress;
	private String userpost;
	private Set orderses = new HashSet(0);

	public Users() {
	}

	public Users(String useracount, String userpasswork, Boolean userstatus, String username, String userphone,
			String useraddress, String userpost, Set orderses) {
		this.useracount = useracount;
		this.userpasswork = userpasswork;
		this.userstatus = userstatus;
		this.username = username;
		this.userphone = userphone;
		this.useraddress = useraddress;
		this.userpost = userpost;
		this.orderses = orderses;
	}

	public Integer getUserid() {
		return this.userid;
	}

	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	public String getUseracount() {
		return this.useracount;
	}

	public void setUseracount(String useracount) {
		this.useracount = useracount;
	}

	public String getUserpasswork() {
		return this.userpasswork;
	}

	public void setUserpasswork(String userpasswork) {
		this.userpasswork = userpasswork;
	}

	public Boolean getUserstatus() {
		return this.userstatus;
	}

	public void setUserstatus(Boolean userstatus) {
		this.userstatus = userstatus;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getUserphone() {
		return this.userphone;
	}

	public void setUserphone(String userphone) {
		this.userphone = userphone;
	}

	public String getUseraddress() {
		return this.useraddress;
	}

	public void setUseraddress(String useraddress) {
		this.useraddress = useraddress;
	}

	public String getUserpost() {
		return this.userpost;
	}

	public void setUserpost(String userpost) {
		this.userpost = userpost;
	}

	public Set getOrderses() {
		return this.orderses;
	}

	public void setOrderses(Set orderses) {
		this.orderses = orderses;
	}

}
